server:
  port: 8080
  
spring:
  #Data Configuration  
  datasource:
    url: jdbc:postgresql://localhost:5432/giasuomt
    username: postgres
    password: khangdeptrai 
  #JPA Configuration
  jpa:
    show-sql: true #để xem câu sql mà nó tự sinh
    generate-ddl: true #để thằng Hibernate tự nhìn Object và tạo database được
    hibernate:
      ddl-auto: create-drop
      # ddl-auto: create-drop   servlet:     multipart:
      enabled: true
      file-size-threshold: 2KB      max-file-size: 200MB      max-request-size: 220MB
      
gsomt:
  app:
    jwt-secret: apiofgsomt
    jwt-duration: 360000000 
amazon:
  endPointURl: https://s3.ap-southeast-1.amazonaws.com/testgsomtcloud/
  accesskey: AKIAUDLYPJWXS2ZHFXZ2                        #tạo user
  secretkey: 5f8YzEv2bbai+UrVJfrdwb9fvwkilpvzHVHS/3Sg       #   
  bucketname: testgsomtcloud
            